# Generated by Django 5.2.8 on 2025-11-15 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_product_is_active_product_percent_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available_stock',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
