# Generated by Django 5.2.8 on 2025-11-17 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_product_available_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='image_large',
            field=models.ImageField(blank=True, null=True, upload_to='store_products/'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_medium',
            field=models.ImageField(blank=True, null=True, upload_to='store_products/'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_thumb',
            field=models.ImageField(blank=True, null=True, upload_to='store_products/'),
        ),
    ]
