# Generated by Django 5.2.8 on 2025-11-30 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_announcement_global_for_all_store_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='about_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='about_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='about_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='about_4',
            field=models.TextField(blank=True, null=True),
        ),
    ]
