# Generated by Django 5.2.8 on 2025-12-10 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_product_about_1_product_about_2_product_about_3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='index_Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading_1', models.CharField(blank=True, max_length=150, null=True)),
                ('heading_2', models.CharField(blank=True, max_length=150, null=True)),
                ('subheading_1', models.CharField(blank=True, max_length=250, null=True)),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='index_content/')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='index_content/')),
                ('section_heading_mission', models.CharField(blank=True, max_length=150, null=True)),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='index_content/')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='index_content/')),
                ('image_5', models.ImageField(blank=True, null=True, upload_to='index_content/')),
                ('fact_heading', models.CharField(blank=True, max_length=150, null=True)),
                ('fact_subheading', models.CharField(blank=True, max_length=250, null=True)),
                ('fact_statement_1', models.CharField(blank=True, max_length=250, null=True)),
                ('fact_statement_2', models.CharField(blank=True, max_length=250, null=True)),
                ('fact_statement_3', models.CharField(blank=True, max_length=250, null=True)),
                ('fact_image_1', models.ImageField(blank=True, null=True, upload_to='index_content/')),
                ('fact_image_2', models.ImageField(blank=True, null=True, upload_to='index_content/')),
                ('fact_image_3', models.ImageField(blank=True, null=True, upload_to='index_content/')),
                ('pricing_heading', models.CharField(blank=True, max_length=150, null=True)),
                ('pricing_subheading', models.CharField(blank=True, max_length=250, null=True)),
                ('monthly_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('annual_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
